#!/bin/bash
#convert-images.sh

IMAGEDIR=$1
NAME=$2
NAMESANSEXT=$3

FILEPATH=$IMAGEDIR/$NAME

cp $FILEPATH $IMAGEDIR/$NAMESANSEXT"_2.jpg"
cp $FILEPATH $IMAGEDIR/$NAMESANSEXT"_3.jpg"
cp $FILEPATH $IMAGEDIR/$NAMESANSEXT"_4.jpg"

convert $IMAGEDIR/$NAMESANSEXT"_2.jpg" -colorspace CMYK $IMAGEDIR/$NAMESANSEXT"_cmyk.jpg"
rm $IMAGEDIR/$NAMESANSEXT"_2.jpg"

convert $IMAGEDIR/$NAMESANSEXT"_3.jpg" -colorspace gray $IMAGEDIR/$NAMESANSEXT"_gray.jpg"
rm $IMAGEDIR/$NAMESANSEXT"_3.jpg"

convert $IMAGEDIR/$NAMESANSEXT"_4.jpg" -quality 80 $IMAGEDIR/$NAMESANSEXT"_web.jpg"
rm $IMAGEDIR/$NAMESANSEXT"_4.jpg"
